env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "go1Aut7kk9hM2KmE5NKczBndAwnQ1C70zxguJo5tFk+qMRg3+Mt3p6Es4xl+qI1DLnqd1qkHw2KrHCVcYNWyLr3ECsvd7BlsfKhSo/zJCth4QtTbm4AwXkEwBO3lTEcCWvlQezP2fJA3o5JIDOR+3AM2TztlyJk+xgutmEXTOy24bYQK2c71roUbjYlPfitRVfQ7rhacrxAZNp3PS8ye1pN26PwE2sZgy+KsWFV9HZx8aB2euva4W+dlr6A7t6VlBi8kQrZcJwNnsTyiYNOJd5M066sVN4LfwxTzm3342YjkbV9h+9lQqlxeFqEQAn3yWyS4MzvUW2LClnjHP3rtDelqQQSlTLuV6fDt/NWPJK430CW2ehp43F9PGuTLCvLXwsLMhNKTasONL7E7kvRS2COD3Gb+cbzJ+qEs0QtHl9ej5nCE5ba+FPPKgpjhstc4xzsSNOE9PoUrcr0zu4M6dYGfwCAQEygExp8fVKfwYzh2Qy0/vrtN7ucHnfPi+0xCFHwSKfjmQbPcRkILr2uq9kU7LbMwHSlPIk5GTHz2TJ4VNmmzRxkrx6buVtF58DhwUB5e2RZ5zWFqtkzLnrmKB3nbszG0NyUcG2+tHTF9hctB+l7bep1vo+DGQD0OyKVW4//h5+FYYwBHG5CMTsHIpYsqJP2ixx1INPVJ4elCU/I="
   
addons:
  coverity_scan:
    project:
      name: "BSravanthi/outreach-portal"
      description: "Your project description here"
    notification_email: sravanthi@vlabs.ac.in    
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: master

    
script:
  - make -j2  
