env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Q/RNwQ0pU89XyUcfNO6LdFJZnUrglYbx77GOf2B4h9TInqNllhpavv9ZNDS/nVl0lhdWE9AsjeuBmVzO8BdHH6oOjuM4UwbekkwMXV7UWYOHkCUsFKQUsEKJbhyHiTaYHzeZYeP9C4aMsBrYssED/BKGgHG0g4Ttqoyga3dvDwDufWqm8r2Ow9PVr3DK7cRxEdGFG9e9xIey0lvGgby52T/HP3hZTEe3cHtjuQGIHizt7/mAus1xG8hVPujmb+RG3uAhI47zL9OdKszrFuvaoJfJrF3/wlKvtr4iM25DOMFZsizy/4XgboKZLqlDmtUwoR+RvaQqzGiszRHO9mEpMJf3LaZXg5Mu6a7OmJw/mfH+z55kMKkjxu/vHTLzq7m7c/Kvh8rsvRD+nYdjo7EzCH+aNVrtyzI+uicEhB0PgUhJEVxOFJGu1Rb9kqgmurUu47JH/fIkln+jI8BvarlUpHfQliqhPQ9DvZ5hGtc3HtesG2jKNMj1kEhFn1Qw/O5UWyLrMy3xdE17zSvMJVJLnhuHj8Eqh3poCXA/fxMCRoemJEo8wO0SBS2PJr6+zAfPED9wAZIqH5Pzhu21F+D0J65IZ3gxBp1puYCqcRGnnMeMHezZBSrSESyW6rzFfQtOeA9Ln90R5I9cXH9DkAcmQqEJcN3o53HgxSvffhzs/CI="
   
addons:
  coverity_scan:
    project:
      name: "BSravanthi/outreach-portal"
      description: "Your project description here"
    notification_email: sravanthi@vlabs.ac.in    
    build_command_prepend: "./configure"
    build_command: "make -j2"
    branch_pattern: master

    
script:
  - make -j2  
